"""add google id to google connections table

Revision ID: 6ce9f8522e85
Revises: b523d3f9d80c
Create Date: 2026-10-10 20:04:52.651105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce9f8522e85'
down_revision: Union[str, Sequence[str], None] = 'b523d3f9d80c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_connection', sa.Column('google_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'google_connection', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'google_connection', type_='unique')
    op.drop_column('google_connection', 'google_id')
    # ### end Alembic commands ###
