"""create google connections table

Revision ID: b523d3f9d80c
Revises: a6f62c230208
Create Date: 2026-10-09 12:53:24.956309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b523d3f9d80c'
down_revision: Union[str, Sequence[str], None] = 'a6f62c230208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_connection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrpt', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrpt', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_google_connection_user')
    )
    op.create_index(op.f('ix_google_connection_user_id'), 'google_connection', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_connection_user_id'), table_name='google_connection')
    op.drop_table('google_connection')
    # ### end Alembic commands ###
